package com.hemajoo.education.wow.queue.commons;

public enum MessageCategoryType
{
    MESSAGE_CATEGORY_EVENT,

    MESSAGE_CATEGORY_EVENT_NOTIFICATION,

    MESSAGE_CATEGORY_EVENT_ARENA,

    MESSAGE_CATEGORY_EVENT_BATTLEGROUND,

    MESSAGE_CATEGORY_EVENT_RAID,

    MESSAGE_CATEGORY_EVENT_DUNGEON,

    MESSAGE_CATEGORY_ACTION_HOUSE,
}
